name: questopia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  go_router: ^11.1.4
  slider_button: ^2.0.0
  flutter_multi_formatter: ^2.11.14
  keyboard_dismisser: ^3.0.0
  pin_code_fields: ^8.0.1
  figma_squircle: ^0.5.3
  cached_network_image: ^3.3.0
  sealed_currencies: ^0.2.2
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  rxdart: ^0.27.7
  get_it: ^7.7.0
  get: ^4.6.5
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  intl: ^0.18.0
  dio: ^5.4.3+1
  supabase_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  email_validator: ^2.1.17
  image_picker: ^1.1.1
  hive: ^2.2.3
  sliver_tools: ^0.2.12
  hive_flutter: ^1.1.0
  flutter_dash: ^1.0.0
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^1.0.8
  permission_handler: ^11.3.1
  mask_text_input_formatter: ^2.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router: ^11.1.4
  custom_lint: ^0.5.3
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/rf_dewi_bold.ttf
          weight: 700
        - asset: fonts/rf_dewi_regular.ttf
          weight: 400
        - asset: fonts/rf_dewi_semibold.ttf
          weight: 600